# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-12 17:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pacients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacient',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Direccion'),
        ),
        migrations.AddField(
            model_name='pacient',
            name='blood',
            field=models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB-', 'AB-'), ('AB+', 'AB+')], default=None, max_length=4, verbose_name='Tipo de sangre'),
        ),
        migrations.AddField(
            model_name='pacient',
            name='cp',
            field=models.IntegerField(blank=True, null=True, verbose_name='Codigo Postal'),
        ),
        migrations.AddField(
            model_name='pacient',
            name='curp',
            field=models.CharField(default=None, max_length=20, verbose_name='CURP'),
        ),
        migrations.AddField(
            model_name='pacient',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Numero de telefono'),
        ),
        migrations.AddField(
            model_name='pacient',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='pacient',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
