# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-26 16:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='first_image',
        ),
        migrations.RemoveField(
            model_name='report',
            name='monocito',
        ),
        migrations.AddField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 4, 26, 16, 15, 38, 735873, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='image',
            field=models.ImageField(default='img/test/img1.jpg', upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='route_report',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='second_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
