# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-26 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20160426_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='pacient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacients.Pacient'),
        ),
    ]
